### ISSUE TITLE
輸入格式問題

### ISSUE THREAD

**Issue by Uranustrong** [NTU-SP/SP2024_HW1_release#2]
助教您好：
我有兩個問題想請問助教：
（ㄧ）請問是否需要考慮一次輸入很多個以'\n'結尾的command? (例如利用pipeline 一次讀入所有command)
（二）使用者可以在輸入的command加很多的space嗎？
謝謝助教撥冗回答。

敬祝 學習順利 身體健康
宋和峻 敬上

**Comment by TehBengYen419** [comment]
同學好，
1. client不會一次輸入多個以'\n'的command
2. testcase不會出現多個space的input

TA
